### ISSUE TITLE
New Startup Page "Options" w/ Configs & Save 

### ISSUE THREAD

**Issue by hrmonarch** [brndmfrd/PFCharacterSheet#14]
Change startup page ("Create/Load") page to "Options."
1. Keep 'Create new character.'
2. Keep 'Load character.'
3. Add 'save' option.
4. Add 'config' settings. 
    \* UI size (sm, med, lg)
    \* Colors & skins

**Comment by brndmfrd** [comment]
UI size and colors and skins have been made into their own, separate, issue.
